# Select project to build
#PROJECT_DIR = sample1
#PROJECT_DIR = thread_metric_idle_baseline
PROJECT_DIR = thread_metric_idle_host_has_guest
#PROJECT_DIR = thread_metric_idle_host_no_guest
#PROJECT_DIR = thread_metric_idle_isotee_guest
#PROJECT_DIR = thread_metric_timeparted_baseline
#PROJECT_DIR = broken_time_part

# Middleware folders
ISOTEE_DIR = ../isotee
RENESAS_FIT_DIR = ../FIT_modified_code
THREAD_METRIC_DIR = ../thread_metric_test_suite

include common/Makefile.project
